### PR TITLE
Draw sample structure

### LINKED ISSUE #4: Create GUI to generate arrays for material properties
This is currently [done manually](https://github.com/zan8simone/PPML---Periodically-Patterned-Multi-Layer/blob/main/examples/OpticalCritical_APL2013_fig3_a.m#L56)

### PR DESCRIPTION
**Pull request by gcapes**
Fix #4

### CODE REVIEW

**Comment by gcapes** [comment]
This needs R2023b, but as an indicator, the example structure looks like this:

sample_structure

**Comment by zan8simone** [comment]
Hi James, good job; I have just 2 comments:
* Perhaps one should specify that the requirement of R2023b is only for enabling some graphical features of the live script example
* The structure rendering should be plotted "upside down", and with a change in x- and z- the coordinates (this is to make things consistent with the manual)

Screenshot 2023-10-09 084853

**Comment by gcapes** [comment]
Ok, I think that's all done now. Do let me know if there's any other changes I should make. Are the colours ok? 

Should look something like this. 
untitled

**Comment by zan8simone** [comment]
Hi James, sorry but it still doesn't match the theory... actually, the green blocks should lie in the region somewhere between 0 and 5 um of the z-coordinate. I try to make this clear as follows (hoping not to introduce more confusion)...:

image

**Comment by gcapes** [comment]
Hi Simone, 
I'm guessing I've missed something here, because with h=4.67 (from the original example), the diagram looks ok to me.
We'd have layer depths of 30, 0.2, 4.67, 4.3, 1 and 30?

**Comment by zan8simone** [comment]
Hi, what I mean (quite difficult to explain in plain text...) is that I am expecting to find, when considering increasing numerical values of z-coordinate, first the superstrate, then a thin patterned layer, then a thick patterned layer, then an unpatterned layer, etc. Instead, I find first the superstrate, and immediately after an unpatterned layer, which is unexpected. It seems that the plot is reversing the layer order...

**Comment by gcapes** [comment]
Ah yes, I understand now. I think this is now fixed?
untitled

**Pull request merged**
