### PR TITLE
Add live script

### LINKED ISSUE #2: Create live script to run OpticalCritical example
- [x] For speed of execution, could reduce the number of incidence angles to e.g. 5. This would need to be presented differently rather than the existing image plot
- [x] Add live script controls for user to change lambda (stripe spacing), and depth (h)
- [x] Separate plotting code out of the `optical_critical` function

### LINKED ISSUE #3: Add 'Open MATLAB Online button' in README
This would open the live script (#2) in MATLAB Online so it could be tried without having to install MATLAB.

### PR DESCRIPTION
**Pull request by gcapes**
Fix #2 
Fix #3

### CODE REVIEW

**Comment by gcapes** [comment]
- [x] Add inputs for nu and theta - set the start, end and step size for both.
- [x] Move live script and supporting functions to subdirectory called 'live_script'
- [x] Fix link formatting for 'open in MATLAB online button'

**Comment by gcapes** [comment]
@zan8simone  I think this is now ready to merge(?)

**Comment by gcapes** [comment]
Adding the directories to the MATLAB path isn't working as intended on Windows/from the live_scripts directory. Need to think of a more robust solution.

**Comment by gcapes** [comment]
@zan8simone 
This should now be fixed.

**Comment by zan8simone** [comment]
not indeed.. this error appears now
image

**Comment by gcapes** [comment]
Hmm, I've not been able to reproduce that error. Could you try once more with the latest code (I've made a couple of extra commits) and a fresh MATLAB session? 
I'm using R2023a rather than R2022b, but the `tiledlayout` function was introduced in 2019b so I doubt that is the problem.

**Comment by gcapes** [comment]
Do you get an error if you execute `tiledlayout("horizontal")` from the MATLAB command window?

**Comment by zan8simone** [comment]
Actually tiledlayout("horizontal") works only from R2023a [https://it.mathworks.com/help/matlab/ref/tiledlayout.html](https://it.mathworks.com/help/matlab/ref/tiledlayout.html)

**Comment by gcapes** [comment]
Well spotted!
However, given the current recommendation is to use `tiledlayout` rather than subplot, and that the demo would run in MATLAB online in the current version, can we go ahead and merge this?

**Pull request merged**
